/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Dani
 */
public class viewOpe extends javax.swing.JFrame {

    /**
     * Creates new form viewOpe
     */
    public viewOpe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jl_numero1 = new javax.swing.JLabel();
        jtf_numero1 = new javax.swing.JTextField();
        jtf_numero2 = new javax.swing.JTextField();
        jl_numero2 = new javax.swing.JLabel();
        jl_resultado = new javax.swing.JLabel();
        jcb_operaciones = new javax.swing.JComboBox<>();
        jb_calculator = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl_numero1.setText("Número1");

        jtf_numero1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtf_numero1MouseClicked(evt);
            }
        });
        jtf_numero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_numero1ActionPerformed(evt);
            }
        });

        jtf_numero2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtf_numero2MouseClicked(evt);
            }
        });
        jtf_numero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_numero2ActionPerformed(evt);
            }
        });

        jl_numero2.setText("Número2");

        jl_resultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_resultado.setText("0.0");
        jl_resultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_resultadoMouseClicked(evt);
            }
        });

        jcb_operaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suma", "Resta", "Multiplicacion", "Division", "Modulo" }));
        jcb_operaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcb_operacionesMouseClicked(evt);
            }
        });
        jcb_operaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_operacionesActionPerformed(evt);
            }
        });

        jb_calculator.setText("Calculator");
        jb_calculator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_calculatorMouseClicked(evt);
            }
        });
        jb_calculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_calculatorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jcb_operaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb_calculator))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_resultado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jl_numero2)
                                    .addComponent(jl_numero1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_numero1)
                                    .addComponent(jtf_numero2))))))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_numero1)
                    .addComponent(jtf_numero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_numero2)
                    .addComponent(jtf_numero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jl_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_operaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_calculator))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_numero1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtf_numero1MouseClicked

    }//GEN-LAST:event_jtf_numero1MouseClicked

    private void jtf_numero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_numero1ActionPerformed

    }//GEN-LAST:event_jtf_numero1ActionPerformed

    private void jtf_numero2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtf_numero2MouseClicked

    }//GEN-LAST:event_jtf_numero2MouseClicked

    private void jtf_numero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_numero2ActionPerformed

    }//GEN-LAST:event_jtf_numero2ActionPerformed

    private void jl_resultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_resultadoMouseClicked

    }//GEN-LAST:event_jl_resultadoMouseClicked

    private void jcb_operacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcb_operacionesMouseClicked

    }//GEN-LAST:event_jcb_operacionesMouseClicked

    private void jcb_operacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_operacionesActionPerformed

    }//GEN-LAST:event_jcb_operacionesActionPerformed

    private void jb_calculatorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_calculatorMouseClicked
        float n1;
        float n2;
        float r;
        n1 = Float.parseFloat(this.jtf_numero1.getText());
        n2 = Float.parseFloat(this.jtf_numero2.getText());
        String indx;
        indx = this.jcb_operaciones.getSelectedItem().toString();
        switch(indx){
            case "Suma":{
                r=n1+n2;
                this.jl_resultado.setText(String.valueOf(r));
                break;
            }
            case "Resta":{
                r=n1-n2;
                this.jl_resultado.setText(String.valueOf(r));
                break;
            }
            case "Multiplicacion":{
                r=n1*n2;
                this.jl_resultado.setText(String.valueOf(r));
                break;
            }
            case "Modulo":{
                r=n1%n2;
                this.jl_resultado.setText(String.valueOf(r));
                break;
            }
            case "Division":{
                r=n1/n2;
                this.jl_resultado.setText(String.valueOf(r));
                break;
            }
            default:{
                this.jl_resultado.setText("Esto no sirve");
            }
        }

    }//GEN-LAST:event_jb_calculatorMouseClicked

    private void jb_calculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_calculatorActionPerformed

    }//GEN-LAST:event_jb_calculatorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewOpe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewOpe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewOpe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewOpe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewOpe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton jb_calculator;
    public javax.swing.JComboBox<String> jcb_operaciones;
    public javax.swing.JLabel jl_numero1;
    public javax.swing.JLabel jl_numero2;
    public javax.swing.JLabel jl_resultado;
    public javax.swing.JTextField jtf_numero1;
    public javax.swing.JTextField jtf_numero2;
    // End of variables declaration//GEN-END:variables
}
